### ISSUE TITLE
Mudar Date para String em todo o projeto

### ISSUE THREAD

**Issue by fdotf97pb** [LailaFerreira/scaj#5]
Marco falou pra deixar String por enquanto, no futuro vai voltar a ser date.

**Comment by LailaFerreira** [comment]
Mudar também nos controllers e telas pois estao usando data como DATE @wagnercampaljf

**Comment by LailaFerreira** [comment]
Algumas estão feitas, mas faz uma busca geral no projeto pra facilitar a mudança
